<?php
$allSets = [
    2023 => [
        [
            'name' => 'Phyrexia: All Will Be One',
            'code' => 'ONE',
            'date' => '2023-02-10',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'The Phyrexians complete their invasion of the multiverse, corrupting planeswalkers with compleation. Set on New Phyrexia, featuring oil counters and the toxic mechanic.',
            'cards' => 479,
            'commander_code' => 'ONC',
            'wotc_url' => 'https://magic.wizards.com/en/products/phyrexia-all-will-be-one',
            'scryfall_url' => 'https://scryfall.com/sets/one',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Phyrexia:_All_Will_Be_One',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Phyrexia+All+Will+Be+One',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/1Fx1A7vxymm7s4Z4gLcy1k/450df16721305a979423149a1bd05052/sFMWiQ9t70_EN.jpg',
        ],
        [
            'name' => 'March of the Machine',
            'code' => 'MOM',
            'date' => '2023-04-21',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'The multiverse unites against the Phyrexian invasion in an epic war across multiple planes. Features the battle card type and team-up legendary creatures.',
            'cards' => 387,
            'commander_code' => 'MOC',
            'wotc_url' => 'https://magic.wizards.com/en/products/march-of-the-machine',
            'scryfall_url' => 'https://scryfall.com/sets/mom',
            'wiki_url' => 'https://mtg.fandom.com/wiki/March_of_the_Machine',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/March+of+the+Machine',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/1YD1uwKFdCTP0xVN9PKkuN/cecf95bbc5b996ae47955645d0ad6e26/ha8fl2n9x4g_1200x630_EN.jpg',
        ],
        [
            'name' => 'The Lord of the Rings: Tales of Middle-earth',
            'code' => 'LTR',
            'date' => '2023-06-23',
            'universe' => 'Universes Beyond',
            'formats' => ['Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Universes Beyond set based on Tolkien\'s The Lord of the Rings trilogy. Features iconic characters, locations and events from Middle-earth with the Ring tempts you mechanic.',
            'cards' => 856,
            'commander_code' => 'LTC',
            'wotc_url' => 'https://magic.wizards.com/en/products/the-lord-of-the-rings-tales-of-middle-earth',
            'scryfall_url' => 'https://scryfall.com/sets/ltr',
            'wiki_url' => 'https://mtg.fandom.com/wiki/The_Lord_of_the_Rings:_Tales_of_Middle-earth',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/The+Lord+of+the+Rings+Tales+of+Middle-earth',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/3UHPSxuvTHz5cUiC2sdpHV/6444431da5f3f3d5cfbeb161a8b19592/M374nf789bfyux-1200x630Op-02.jpg',
        ],
        [
            'name' => 'Wilds of Eldraine',
            'code' => 'WOE',
            'date' => '2023-09-08',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Return to the fairy-tale plane of Eldraine after the Phyrexian invasion left it wilder and more untamed. Features adventure cards and the roles mechanic.',
            'cards' => 381,
            'commander_code' => 'WOC',
            'wotc_url' => 'https://magic.wizards.com/en/products/wilds-of-eldraine',
            'scryfall_url' => 'https://scryfall.com/sets/woe',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Wilds_of_Eldraine',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Wilds+of+Eldraine',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/1RDStTg5tpc3a8tfZyY1W6/500ab988192004b668cfba5ae5627083/vnjieqejqun_EN.jpg',
        ],
        [
            'name' => 'The Lost Caverns of Ixalan',
            'code' => 'LCI',
            'date' => '2023-11-17',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Explorers delve into a vast underground cavern system beneath Ixalan, discovering ancient civilizations and Cosmium. Features the discover, craft and descend mechanics.',
            'cards' => 416,
            'commander_code' => 'LCC',
            'wotc_url' => 'https://magic.wizards.com/en/products/the-lost-caverns-of-ixalan',
            'scryfall_url' => 'https://scryfall.com/sets/lci',
            'wiki_url' => 'https://mtg.fandom.com/wiki/The_Lost_Caverns_of_Ixalan',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/The+Lost+Caverns+of+Ixalan',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/4uilLVT7c3wWb2modm6pAW/73eb86eb4aa66648fb0093620b4cb627/Gib943JIBJ_EN.jpg',
            'image_pos' => '30% center',
        ],
    ],
    2024 => [
        [
            'name' => 'Murders at Karlov Manor',
            'code' => 'MKM',
            'date' => '2024-02-09',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A murder mystery set on Ravnica where detectives investigate crimes across the city\'s guilds. Features clue tokens, suspect, collect evidence and disguise mechanics.',
            'cards' => 451,
            'commander_code' => 'MKC',
            'wotc_url' => 'https://magic.wizards.com/en/products/murders-at-karlov-manor',
            'scryfall_url' => 'https://scryfall.com/sets/mkm',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Murders_at_Karlov_Manor',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Murders+at+Karlov+Manor',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/3IMaT71Qw3BaV9vgbz8p7I/e952e2f4df2516ac07bad93df9e0efa5/9jf6xcrt_1200x630_Meta_EN.jpg',
        ],
        [
            'name' => 'Outlaws of Thunder Junction',
            'code' => 'OTJ',
            'date' => '2024-04-19',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A Western-themed heist set on the frontier plane of Thunder Junction, where outlaws and criminals converge. Features the plot, spree and crime mechanics.',
            'cards' => 374,
            'commander_code' => 'OTC',
            'wotc_url' => 'https://magic.wizards.com/en/products/outlaws-of-thunder-junction',
            'scryfall_url' => 'https://scryfall.com/sets/otj',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Outlaws_of_Thunder_Junction',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Outlaws+of+Thunder+Junction',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/2Jcnqi6tnVO40eKc8XvFtT/b2d7caccf928290b96106117a1cb00bd/1200x630_Meta_EN.jpg',
        ],
        [
            'name' => 'Assassin\'s Creed',
            'code' => 'ACR',
            'date' => '2024-07-05',
            'universe' => 'Universes Beyond',
            'formats' => ['Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Universes Beyond set based on Ubisoft\'s Assassin\'s Creed franchise spanning multiple historical eras. Features characters, artifacts and locations with the freerunning mechanic.',
            'cards' => 309,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/assassins-creed',
            'scryfall_url' => 'https://scryfall.com/sets/acr',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Assassin%27s_Creed',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Assassins+Creed',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/4gQEsQ2gjlPaPAeUHMouf6/25f27c6c88e04c496f0c953f83affb0c/DgedjelvvBvVv3800.jpg',
        ],
        [
            'name' => 'Bloomburrow',
            'code' => 'BLB',
            'date' => '2024-08-02',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A whimsical plane inhabited entirely by anthropomorphic woodland animals with no humans. Features the valiant, offspring and forage mechanics.',
            'cards' => 398,
            'commander_code' => 'BLC',
            'wotc_url' => 'https://magic.wizards.com/en/products/bloomburrow',
            'scryfall_url' => 'https://scryfall.com/sets/blb',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Bloomburrow',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Bloomburrow',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/4ftiCqKWLwH3dR5IfYpEUJ/17d49c991dd4e0c0c075a85c701ddc87/bBe3lL3eEE_EN.jpg',
        ],
        [
            'name' => 'Duskmourn: House of Horror',
            'code' => 'DSK',
            'date' => '2024-09-27',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A horror-themed set in an endless nightmarish haunted house that has consumed an entire plane. Features the rooms enchantment subtype, survival, eerie and delirium mechanics.',
            'cards' => 419,
            'commander_code' => 'DSC',
            'wotc_url' => 'https://magic.wizards.com/en/products/duskmourn-house-of-horror',
            'scryfall_url' => 'https://scryfall.com/sets/dsk',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Duskmourn:_House_of_Horror',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Duskmourn+House+of+Horror',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/5Z6XZZT3g4u5nsc4ConHgE/eec8bf6872a0934bed24b3f0cbb027f3/D3277KkJfzzXxx.jpg',
        ],
        [
            'name' => 'Foundations',
            'code' => 'FDN',
            'date' => '2024-11-15',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A core set designed as the new entry point for Magic, featuring beloved reprints and new cards that remain Standard-legal until at least 2029.',
            'cards' => 730,
            'commander_code' => 'FDC',
            'wotc_url' => 'https://magic.wizards.com/en/products/foundations',
            'scryfall_url' => 'https://scryfall.com/sets/fdn',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Foundations',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Foundations',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/41a4naXtA7ydcegvtpOkp0/a222210b5a073deacf7e41ca4c6040ed/Meta-Image_FDN_EN.jpg',
        ],
    ],
    2025 => [
        [
            'name' => 'Aetherdrift',
            'code' => 'DFT',
            'date' => '2025-02-14',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'A high-speed racing set where competitors race magical vehicles across the multiverse through the Aether. Features start your engines and vehicle-focused mechanics.',
            'cards' => 553,
            'commander_code' => 'DRC',
            'wotc_url' => 'https://magic.wizards.com/en/products/aetherdrift',
            'scryfall_url' => 'https://scryfall.com/sets/dft',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Aetherdrift',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Aetherdrift',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/2CFXBCc6fvIRKRzJT8fQ19/f945c8454d50b31df62f21ed8409c47a/Meta-Image_DFT.jpg',
        ],
        [
            'name' => 'Tarkir: Dragonstorm',
            'code' => 'TDM',
            'date' => '2025-04-11',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Return to the plane of Tarkir where dragons reign supreme and the clans must adapt to survive under dragonlords. Features dragon-focused mechanics and clan identities.',
            'cards' => 427,
            'commander_code' => 'TDC',
            'wotc_url' => 'https://magic.wizards.com/en/products/tarkir-dragonstorm',
            'scryfall_url' => 'https://scryfall.com/sets/tdm',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Tarkir:_Dragonstorm',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Tarkir+Dragonstorm',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/1neheUd9kzXJPLrtgyyMh1/38a4c66d7754019988d3c056610b79c2/rhsasj4hshl_1200x630.jpg',
        ],
        [
            'name' => 'Final Fantasy',
            'code' => 'FIN',
            'date' => '2025-06-13',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Universes Beyond set based on Square Enix\'s Final Fantasy franchise, featuring iconic characters, jobs and summons. The first Universes Beyond set to be Standard-legal.',
            'cards' => 599,
            'commander_code' => 'FIC',
            'wotc_url' => 'https://magic.wizards.com/en/products/final-fantasy',
            'scryfall_url' => 'https://scryfall.com/sets/fin',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Final_Fantasy',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Final+Fantasy',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/7xbcdQkzn4CSDCeKpz0tTJ/cb6998fe65114c1146f90f6d9eb4b4b8/M23bfxta44-1023x700.jpg',
        ],
        [
            'name' => 'Edge of Eternities',
            'code' => 'EOE',
            'date' => '2025-08-01',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Explores the boundaries of time and eternity across the multiverse. Features new mechanics centered around temporal and planar themes.',
            'cards' => 400,
            'commander_code' => 'EOC',
            'wotc_url' => 'https://magic.wizards.com/en/products/edge-of-eternities',
            'scryfall_url' => 'https://scryfall.com/sets/eoe',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Edge_of_Eternities',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Edge+of+Eternities',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/88v8OQA5uiNrEeDIzEoPP/3d146264360fff6f99a3e4e904a49983/5rojh3s27o_1200x630_EN.png',
        ],
        [
            'name' => 'Marvel\'s Spider-Man',
            'code' => 'SPM',
            'date' => '2025-09-26',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Universes Beyond set featuring Marvel\'s Spider-Man and related characters, villains and storylines. Brings the web-slinger into Standard-legal Magic.',
            'cards' => 286,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/marvel/spider-man',
            'scryfall_url' => 'https://scryfall.com/sets/spm',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Marvel%27s_Spider-Man',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Marvels+Spider-Man',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/2inGLgSwsh3acZOF8wT5E2/2fffba1cd300c264335157d8a03396f5/V2ceroolIconer739GHK.jpg',
        ],
        [
            'name' => 'Avatar: The Last Airbender',
            'code' => 'TLA',
            'date' => '2025-11-21',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Universes Beyond set based on the beloved animated series. Features bending disciplines, nations and characters from the Avatar universe.',
            'cards' => 394,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/avatar-the-last-airbender',
            'scryfall_url' => 'https://scryfall.com/sets/tla',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Avatar:_The_Last_Airbender',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Avatar+The+Last+Airbender',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/tC0YRhKxVTAnWQxxZWTVO/1fc2dbdd07619e9c9634366e76b78631/mGc3329oOlo_TLA.jpg',
        ],
    ],
    2026 => [
        [
            'name' => 'Lorwyn Eclipsed',
            'code' => 'ECL',
            'date' => '2026-01-23',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Return to the plane of Lorwyn/Shadowmoor where the twin realities have fused. Celtic folklore-inspired setting featuring faeries, kithkin, treefolk and other classic Lorwyn creature types.',
            'cards' => 417,
            'commander_code' => 'ECC',
            'wotc_url' => 'https://magic.wizards.com/en/products/lorwyn-eclipsed',
            'scryfall_url' => 'https://scryfall.com/sets/ecl',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Lorwyn_Eclipsed',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Lorwyn+Eclipsed',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/1esMQz3zTftlaApno90kWP/843a60ea4276ac7b940231a4f10fb506/3H8hMTEhhnho_EN_1200x630.png',
        ],
        [
            'name' => 'Teenage Mutant Ninja Turtles',
            'code' => 'TMT',
            'date' => '2026-03-06',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Crossover drawing from the entire history of TMNT. Features original artist Kevin Eastman artwork. Includes mechanics with +1/+1 counters and Mutagen tokens.',
            'cards' => null,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/teenage-mutant-ninja-turtles',
            'scryfall_url' => 'https://scryfall.com/sets/tmt',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Teenage_Mutant_Ninja_Turtles',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Teenage+Mutant+Ninja+Turtles',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/2DFJSlgguZR2IXMVwqwEPK/4fd9826889e6ff1edaf422c00526fc39/S3W3R00Z3_1200x630.jpg',
        ],
        [
            'name' => 'Secrets of Strixhaven',
            'code' => 'SOS',
            'date' => '2026-04-24',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Return to Strixhaven University on the plane of Arcavios. Students explore off-campus life. Features Mystical Archive bonus sheets with English and Japanese frame variants. Five Commander decks.',
            'cards' => null,
            'commander_code' => 'SOC',
            'wotc_url' => 'https://magic.wizards.com/en/products/secrets-of-strixhaven',
            'scryfall_url' => 'https://scryfall.com/sets/sos',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Secrets_of_Strixhaven',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Secrets+of+Strixhaven',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/349NrvFBupiNlvI0X9bJZV/e9b515d15871e4dea0d94b1de5e671d2/aGSsV8XgZARtbGS_EN_1200x630.png',
        ],
        [
            'name' => 'Marvel Super Heroes',
            'code' => 'MSH',
            'date' => '2026-06-26',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Features Marvel Comics characters including Captain America, Black Panther, Doctor Doom and more. Four Commander decks. Products include Scene Boxes, Jumpstart Boosters and a Beginner Box.',
            'cards' => null,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/marvel/marvel-super-heroes',
            'scryfall_url' => 'https://scryfall.com/sets/msh',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Marvel_Super_Heroes',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Marvel+Super+Heroes',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/46nBs6K9GAlWhsVV1lh1GG/619d98c30b73aa99fd934cb7968a6445/uvb864agiy_1200x630.jpg',
        ],
        [
            'name' => 'The Hobbit',
            'code' => 'HOB',
            'date' => '2026-08-14',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Return to Middle-earth focused on Tolkien\'s The Hobbit. Adventures include battling Trolls and confronting Smaug. Follows the earlier Lord of the Rings: Tales of Middle-earth set.',
            'cards' => null,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/the-hobbit',
            'scryfall_url' => 'https://scryfall.com/sets/hob',
            'wiki_url' => 'https://mtg.fandom.com/wiki/The_Hobbit',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/The+Hobbit',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/16BCmsqkZJM1L7AhsXjrcK/f5d55eb1bd6f07fd9f5278ae24a3f6e4/94bnieberugboa.jpg',
        ],
        [
            'name' => 'Reality Fracture',
            'code' => 'RFR',
            'date' => '2026-10-02',
            'universe' => 'Magic Original',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Epic conclusion of the current Magic story arc featuring a showdown in the Meditation Realm. Concludes the overarching storyline building across recent sets.',
            'cards' => null,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/reality-fracture',
            'scryfall_url' => 'https://scryfall.com/sets/rfr',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Reality_Fracture',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Reality+Fracture',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/2IgS7xB7jBNRBKfZe07fk0/2864dddcb2b6bb80ca2ed8912a4fde20/aGSsV8XgZARtbGS__1200x630_EN.jpg',
        ],
        [
            'name' => 'Star Trek',
            'code' => 'STK',
            'date' => '2026-11-20',
            'universe' => 'Universes Beyond',
            'formats' => ['Standard', 'Pioneer', 'Modern', 'Legacy', 'Vintage', 'Commander'],
            'description' => 'Features characters, stories and spaceships from the entire Star Trek franchise. Further details to be revealed closer to release.',
            'cards' => null,
            'commander_code' => null,
            'wotc_url' => 'https://magic.wizards.com/en/products/star-trek',
            'scryfall_url' => 'https://scryfall.com/sets/stk',
            'wiki_url' => 'https://mtg.fandom.com/wiki/Star_Trek',
            'goldfish_url' => 'https://www.mtggoldfish.com/sets/Star+Trek',
            'image' => 'https://images.ctfassets.net/s5n2t79q9icq/4HybLR2hYLHVEeQZAcAFNh/0fa0cd37e107805da4b65bf7cb9fcd16/iuy892euoi_1200x630.jpg',
            'image_pos' => '15% center',
        ],
    ],
];
